# pipeline definition
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pipeline?view=azure-pipelines#remarks

# pr trigger
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines#pr-autocancel-branches-paths-drafts

# variable groups
# https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml

# Integrate Bicep with Azure Pipelines
# https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/add-template-to-azure-pipelines?tabs=CLI

name: cicd

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*

pool: 
  vmImage: ubuntu-latest
  
stages:
  - stage: build
    jobs:
      - job:
        steps:
          - script: curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 ; chmod +x ./bicep ; sudo mv ./bicep /usr/local/bin/bicep ; bicep --version
            displayName: "Install Bicep."

          - script: mkdir dist ; bicep build src/main.bicep --outdir dist 
            displayName: "Build ARM Templates (main)."

          - script: mkdir -p dist/tools/peerVnetById ; bicep build src/tools/peerVnetById/main.bicep --outdir dist/tools/peerVnetById
            displayName: "Build ARM Templates (tools)."            

          - publish: dist
            displayName: "Publish build artifacts."
            artifact: armtemplates     

  - stage: dev
    dependsOn:
      - build
    variables:
      - group: dev
    jobs:
      - deployment:
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo $(environmentName)
                  displayName: "Example build step."    

  - stage: uat
    dependsOn:
      - build
    variables:
      - group: uat
    jobs:
      - deployment:      
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo $(environmentName) 
                  displayName: "Example build step."    

  - stage: prd
    dependsOn: 
      - uat
    variables:
      - group: prd
    jobs:
      - deployment:      
        environment: prd
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: "Download build artifacts."
                  artifact: armtemplates
                - task: AzureCLI@2
                  displayName: "Create ARM deployment."
                  inputs:
                    azureSubscription: AzureServiceConnection
                    scriptLocation: inlineScript
                    scriptType: bash
                    inlineScript: |
                      az deployment sub create --subscription $(subscriptionId) --location $(location) --template-file ../armtemplates/main.json --name main-$(location)
