name: cicd

on:
  push:
    branches:
      - main
    paths:
      - 'src/*'
  
  pull_request:
    branches:
      - main
    paths:
      - 'src/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    name: Build and upload templates
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install bicep tooling
        run: |
          # Fetch the latest Bicep CLI binary
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          # Mark it as executable
          chmod +x ./bicep
          # Add bicep to your PATH (requires admin)
          sudo mv ./bicep /usr/local/bin/bicep
          # Verify you can now access the 'bicep' command
          bicep --version
          # Done!

      - name: Build bicep files
        run: |
          mkdir -p dst/tools/peerVnetById
          bicep build src/main.bicep --outdir dst 
          bicep build src/tools/peerVnetById/main.bicep --outdir dst/tools/peerVnetById

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: arm-templates
          path: dst

  dev:
    name: Deploy to dev
    if: github.event_name == 'pull_request'
    needs: 
      - build
    environment: 
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: arm-templates
          path: dst

      - name: Deploy to Australia East region
        run: echo deploying to dev

  uat:
    name: Deploy to uat
    if: github.event.ref == 'refs/heads/main'
    needs: 
      - build
    environment: 
      name: uat
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: arm-templates
          path: dst

      - name: Deploy to Australia East region
        run: echo deploying to uat

  prd:
    name: Deploy to prd
    needs: 
      - uat
    environment: 
      name: prd
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: arm-templates
          path: dst

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

      - name: Deploy to Australia East region
        id: deployaue
        uses: azure/arm-deploy@v1
        with:
          deploymentName: aue-core-net
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: australiaeast
          template: dst/main.json

      - name: Display aue template outputs
        run: echo ${{ steps.deployaue.outputs.vnetId_hub }}          

      - name: Deploy to Australia Southeast region
        id: deployase
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ase-core-net
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: australiasoutheast
          template: dst/main.json  

      - name: Display ase template outputs
        run: echo ${{ steps.deployase.outputs.vnetId_hub }}       

      - name: Peer aue hub to ase hub
        uses: azure/arm-deploy@v1
        with:
          deploymentName: aue-core-net-peerhubs
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: australiaeast
          template: dst/tools/peerVnetById/main.json
          parameters: vnetId=${{ steps.deployaue.outputs.vnetId_hub }} remoteVnetId=${{ steps.deployase.outputs.vnetId_hub }}

      - name: Peer ase hub to aue hub
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ase-core-net-peerhubs
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          region: australiasoutheast
          template: dst/tools/peerVnetById/main.json
          parameters: vnetId=${{ steps.deployase.outputs.vnetId_hub }} remoteVnetId=${{ steps.deployaue.outputs.vnetId_hub }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_APPA }}      

      - name: Seed APPA aue subscription
        uses: azure/arm-deploy@v1
        with:
          deploymentName: aue-core-net
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_APPA }}
          region: australiaeast
          template: dst/main.json
          parameters: onlySpokeTemplates=true

      - name: Seed APPA ase subscription
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ase-core-net
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_APPA }}
          region: australiasoutheast
          template: dst/main.json
          parameters: onlySpokeTemplates=true              